// Seed content (SEED.md). Kept as data, separate from the runner logic
// (SEED "treat the seed itself as data") — typed arrays the generic upsert
// runner consumes. All values are config and meant to be tuned live afterwards.

import type {
  Skill,
  Item,
  Rarity,
  Activity,
  Recipe,
  Monster,
  HousingFeature,
  GlobalBoost,
} from '@eishera/shared';

export interface GameConfigSeed {
  key: string;
  value: unknown;
  description: string;
}

export const gameConfig: GameConfigSeed[] = [
  { key: 'tick_seconds', value: 6, description: 'action / tick duration' },
  { key: 'starting_max_actions', value: 1800, description: 'default max_actions for new players' },
  { key: 'xp_curve', value: { B: 60, p: 1.4 }, description: 'xpToNext(L) = round(B * L^p)' },
  {
    key: 'xp_per_action',
    value: 10,
    description: 'flat XP per action (recipe base_xp may override)',
  },
  { key: 'yield_slope', value: 0.02, description: 'yieldMult(L) = 1 + L * slope' },
  {
    key: 'rare',
    value: { base: 0.005, step: 0.0005, cap: 0.1 },
    description: 'pRare(L)=min(cap,base+L*step)',
  },
  { key: 'crit_chance_base', value: 0.05, description: 'base combat crit chance' },
  { key: 'crit_multiplier', value: 2, description: 'per-round crit damage multiplier' },
  { key: 'max_rounds', value: 200, description: 'per-fight round cap; reaching it = loss' },
  {
    key: 'combat_coeffs',
    value: {
      dmg_per_str: 1.0,
      hp_per_vit: 10,
      mitigation_per_def: 0.5,
      dodge_per_eva: 0.4,
      accuracy_per_dex: 0.5,
      crit_per_dex: 0.001,
      crit_per_luck: 0.002,
    },
    description: 'how effective stats map to duel values',
  },
  { key: 'rarity_luck_shift', value: 0.02, description: 'rarity reweight per LUCK (drops)' },
  {
    key: 'rarity_quality_shift',
    value: 0.03,
    description: 'rarity reweight per craft_quality (crafts)',
  },
  {
    key: 'stat_per_level',
    value: { str: 2, vit: 2, def: 1, eva: 1, dex: 1, luck: 1 },
    description: 'base-stat points per combat level-up',
  },
  {
    key: 'random_stat_gain_chance',
    value: 0.002,
    description: 'chance per battle action to gain a stat point',
  },
  {
    key: 'cancel_penalty',
    value: 0.15,
    description: 'housing-upgrade cancel penalty (refund = 1 - this)',
  },
  { key: 'outage_threshold_seconds', value: 30, description: 'live-clock gap treated as downtime' },
  { key: 'market_fee', value: 0, description: 'market transaction fee fraction' },
  {
    // Potion code → active effect (SEED §8.1). Config-driven so it stays data,
    // not code (SPEC §2.7). Consuming the potion creates a player_active_effects row.
    key: 'potion_effects',
    value: {
      power_potion: {
        effect_type: 'combat_all',
        magnitude: 0.2,
        duration_seconds: 1800,
        stacking: 'highest',
      },
      yield_potion: {
        effect_type: 'gather_yield',
        magnitude: 0.25,
        duration_seconds: 1800,
        stacking: 'highest',
      },
    },
    description: 'potion code → { effect_type, magnitude, duration_seconds, stacking }',
  },
];

export const skills: Skill[] = [
  { id: 1, code: 'mining', name: 'Mining' },
  { id: 2, code: 'quarrying', name: 'Quarrying' },
  { id: 3, code: 'hunting', name: 'Hunting' },
  { id: 4, code: 'crafting', name: 'Crafting' },
  { id: 5, code: 'alchemy', name: 'Alchemy' },
  { id: 6, code: 'combat', name: 'Combat' },
];

const raw = (id: number, code: string, name: string): Item => ({
  id,
  code,
  name,
  tradable: true,
  equip_slot: null,
  base_stats: null,
  req_level: null,
  salvage_yield: null,
});

export const items: Item[] = [
  raw(100, 'ore', 'Iron ore'),
  raw(101, 'stone', 'Stone'),
  raw(102, 'food', 'Food'),
  raw(103, 'hide', 'Hide'),
  {
    id: 200,
    code: 'sword',
    name: 'Sword',
    tradable: true,
    equip_slot: 'weapon',
    base_stats: { str: 12, dex: 5 },
    req_level: 1,
    salvage_yield: { iron_scrap: 2 },
  },
  {
    id: 201,
    code: 'armor',
    name: 'Armor',
    tradable: true,
    equip_slot: 'armor',
    base_stats: { def: 10, vit: 8 },
    req_level: 5,
    salvage_yield: { iron_scrap: 2, hide: 1 },
  },
  {
    id: 202,
    code: 'tool',
    name: 'Tool',
    tradable: true,
    equip_slot: 'tool',
    base_stats: { gather_yield: 0.1 },
    req_level: 1,
    salvage_yield: { iron_scrap: 1 },
  },
  raw(300, 'power_potion', 'Power potion'),
  raw(301, 'yield_potion', 'Yield potion'),
  raw(400, 'monster_bone', 'Monster bone'),
  raw(401, 'dragon_scale', 'Dragon scale'),
  raw(402, 'iron_scrap', 'Iron scrap'),
];

export const rarities: Rarity[] = [
  {
    tier: 1,
    code: 'common',
    name: 'Common',
    weight: 1000,
    roll_min: 0.75,
    roll_max: 0.95,
    color: 'gray',
  },
  {
    tier: 2,
    code: 'uncommon',
    name: 'Uncommon',
    weight: 400,
    roll_min: 0.9,
    roll_max: 1.1,
    color: 'green',
  },
  {
    tier: 3,
    code: 'rare',
    name: 'Rare',
    weight: 120,
    roll_min: 1.05,
    roll_max: 1.25,
    color: 'blue',
  },
  {
    tier: 4,
    code: 'unique',
    name: 'Unique',
    weight: 30,
    roll_min: 1.2,
    roll_max: 1.4,
    color: 'purple',
  },
  {
    tier: 5,
    code: 'legendary',
    name: 'Legendary',
    weight: 6,
    roll_min: 1.35,
    roll_max: 1.55,
    color: 'amber',
  },
  {
    tier: 6,
    code: 'mythic',
    name: 'Mythic',
    weight: 1,
    roll_min: 1.5,
    roll_max: 1.75,
    color: 'red',
  },
];

export const activities: Activity[] = [
  { id: 1, code: 'mine', name: 'Mine', skill_id: 1, archetype: 'transform' },
  { id: 2, code: 'quarry', name: 'Quarry', skill_id: 2, archetype: 'transform' },
  { id: 3, code: 'hunt', name: 'Hunt', skill_id: 3, archetype: 'transform' },
  { id: 4, code: 'craft', name: 'Craft', skill_id: 4, archetype: 'transform' },
  { id: 5, code: 'brew', name: 'Brew', skill_id: 5, archetype: 'transform' },
  { id: 6, code: 'battle', name: 'Battle', skill_id: 6, archetype: 'combat' },
];

export const recipes: Recipe[] = [
  {
    id: 1,
    activity_id: 1,
    code: 'ore',
    name: 'Mine ore',
    req_level: 1,
    base_xp: 10,
    inputs: [],
    outputs: [{ item: 'ore', qty: 1, chance: 1.0 }],
  },
  {
    id: 2,
    activity_id: 2,
    code: 'stone',
    name: 'Quarry stone',
    req_level: 1,
    base_xp: 10,
    inputs: [],
    outputs: [{ item: 'stone', qty: 1, chance: 1.0 }],
  },
  {
    id: 3,
    activity_id: 3,
    code: 'game',
    name: 'Hunt game',
    req_level: 1,
    base_xp: 10,
    inputs: [],
    outputs: [
      { item: 'food', qty: 1, chance: 1.0 },
      { item: 'hide', qty: 1, chance: 0.5 },
    ],
  },
  {
    id: 4,
    activity_id: 4,
    code: 'sword',
    name: 'Craft sword',
    req_level: 1,
    base_xp: 15,
    inputs: [
      { item: 'ore', qty: 3 },
      { item: 'stone', qty: 1 },
    ],
    outputs: [{ item: 'sword', qty: 1, chance: 1.0 }],
  },
  {
    id: 5,
    activity_id: 4,
    code: 'armor',
    name: 'Craft armor',
    req_level: 5,
    base_xp: 18,
    inputs: [
      { item: 'ore', qty: 2 },
      { item: 'hide', qty: 3 },
    ],
    outputs: [{ item: 'armor', qty: 1, chance: 1.0 }],
  },
  {
    id: 6,
    activity_id: 5,
    code: 'power_potion',
    name: 'Brew power potion',
    req_level: 1,
    base_xp: 15,
    inputs: [{ item: 'food', qty: 2 }],
    outputs: [{ item: 'power_potion', qty: 1, chance: 1.0 }],
  },
  {
    id: 7,
    activity_id: 5,
    code: 'yield_potion',
    name: 'Brew yield potion',
    req_level: 3,
    base_xp: 15,
    inputs: [
      { item: 'food', qty: 2 },
      { item: 'ore', qty: 1 },
    ],
    outputs: [{ item: 'yield_potion', qty: 1, chance: 1.0 }],
  },
];

export const monsters: Monster[] = [
  {
    id: 1,
    tier: 1,
    name: 'Goblin',
    hp: 100,
    attack: 8,
    accuracy: 70,
    evasion: 10,
    xp: 12,
    gold_min: 5,
    gold_max: 10,
    loot: [{ item: 'monster_bone', chance: 0.1 }],
  },
  {
    id: 2,
    tier: 2,
    name: 'Orc',
    hp: 350,
    attack: 22,
    accuracy: 75,
    evasion: 12,
    xp: 30,
    gold_min: 12,
    gold_max: 25,
    loot: [
      { item: 'monster_bone', chance: 0.15 },
      { item: 'iron_scrap', chance: 0.05 },
    ],
  },
  {
    id: 3,
    tier: 3,
    name: 'Troll',
    hp: 1000,
    attack: 55,
    accuracy: 80,
    evasion: 15,
    xp: 70,
    gold_min: 30,
    gold_max: 60,
    loot: [
      { item: 'iron_scrap', chance: 0.12 },
      { item: 'monster_bone', chance: 0.2 },
    ],
  },
  {
    id: 4,
    tier: 4,
    name: 'Wyvern',
    hp: 2500,
    attack: 120,
    accuracy: 85,
    evasion: 25,
    xp: 150,
    gold_min: 70,
    gold_max: 140,
    loot: [
      { item: 'iron_scrap', chance: 0.15 },
      { item: 'dragon_scale', chance: 0.03 },
    ],
  },
  {
    id: 5,
    tier: 5,
    name: 'Dragon',
    hp: 6000,
    attack: 280,
    accuracy: 90,
    evasion: 30,
    xp: 300,
    gold_min: 150,
    gold_max: 400,
    loot: [
      { item: 'dragon_scale', chance: 0.08 },
      { item: 'iron_scrap', chance: 0.2 },
    ],
  },
];

export const housingFeatures: HousingFeature[] = [
  {
    id: 1,
    code: 'mine_shaft',
    name: 'Mine shaft',
    bonus_type: 'gather_yield',
    max_level: 50,
    cost_base: 100,
    cost_growth: 1.6,
    duration_base: 300,
    duration_growth: 1.7,
    bonus_base: 0.0,
    bonus_growth: 0.01,
    cost_resources: { ore: 5, stone: 5 },
  },
  {
    id: 2,
    code: 'pantry',
    name: 'Pantry',
    bonus_type: 'food_yield',
    max_level: 50,
    cost_base: 100,
    cost_growth: 1.6,
    duration_base: 300,
    duration_growth: 1.7,
    bonus_base: 0.0,
    bonus_growth: 0.01,
    cost_resources: { food: 8 },
  },
  {
    id: 3,
    code: 'workshop',
    name: 'Workshop',
    bonus_type: 'craft_quality',
    max_level: 50,
    cost_base: 120,
    cost_growth: 1.6,
    duration_base: 320,
    duration_growth: 1.7,
    bonus_base: 0.0,
    bonus_growth: 0.01,
    cost_resources: { ore: 6, stone: 4 },
  },
  {
    id: 4,
    code: 'treasury',
    name: 'Treasury',
    bonus_type: 'rare_drop',
    max_level: 50,
    cost_base: 150,
    cost_growth: 1.7,
    duration_base: 400,
    duration_growth: 1.8,
    bonus_base: 0.0,
    bonus_growth: 0.005,
    cost_resources: { ore: 4, stone: 4, food: 4 },
  },
  {
    id: 5,
    code: 'training_hall',
    name: 'Training hall',
    bonus_type: 'combat_all',
    max_level: 50,
    cost_base: 130,
    cost_growth: 1.65,
    duration_base: 350,
    duration_growth: 1.75,
    bonus_base: 0.0,
    bonus_growth: 0.02,
    cost_resources: { food: 6, hide: 4 },
  },
];

export const globalBoosts: GlobalBoost[] = [
  {
    id: 1,
    code: 'xp_surge_24h',
    name: 'XP surge (24h)',
    effect_type: 'xp',
    magnitude: 0.5,
    duration_seconds: 86400,
    default_source: 'token',
  },
  {
    id: 2,
    code: 'harvest_boon_12h',
    name: 'Harvest boon (12h)',
    effect_type: 'gather_yield',
    magnitude: 0.3,
    duration_seconds: 43200,
    default_source: 'token',
  },
  {
    id: 3,
    code: 'battle_fury_1h',
    name: 'Battle fury (1h)',
    effect_type: 'combat_all',
    magnitude: 0.25,
    duration_seconds: 3600,
    default_source: 'event',
  },
  {
    id: 4,
    code: 'boss_fortune_2h',
    name: 'Boss spoils: fortune',
    effect_type: 'rare_drop',
    magnitude: 0.1,
    duration_seconds: 7200,
    default_source: 'world_boss',
  },
  {
    id: 5,
    code: 'veterans_edge',
    name: "Veteran's edge",
    effect_type: 'xp',
    magnitude: 0.1,
    duration_seconds: null,
    default_source: 'token',
  },
];
